name: base
channels:
  - local
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.0.5
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2025.1.31
  - catalogue=2.0.6
  - certifi=2024.8.30
  - cffi=1.15.0
  - chardet=4.0.0
  - charset-normalizer=2.0.12
  - click=8.0.4
  - cmake=3.22.3
  - colorama=0.4.4
  - conda=4.12.0
  - conda-build=3.21.8
  - conda-package-handling=1.8.1
  - cryptography=36.0.2
  - cymem=2.0.6
  - cython-blis=0.7.7
  - dataclasses=0.8
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.4.8
  - filelock=3.6.0
  - glob2=0.7
  - icu=70.1
  - idna=3.3
  - ipython=8.2.0
  - jedi=0.18.1
  - jinja2=3.1.1
  - keyutils=1.6.1
  - krb5=1.19.3
  - langcodes=3.3.0
  - ld_impl_linux-64=2.36.1
  - libarchive=3.5.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.82.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblief=0.11.5
  - libllvm10=10.0.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.20
  - libprotobuf=3.20.1
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libuuid=2.32.1
  - libuv=1.43.0
  - libxml2=2.9.13
  - libzlib=1.2.11
  - llvm-openmp=13.0.1
  - llvmlite=0.36.0
  - lz4-c=1.9.3
  - lzo=2.10
  - magma-cuda110=2.5.2
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.3
  - mkl=2019.5
  - mkl-include=2019.5
  - mock=4.0.3
  - murmurhash=1.0.6
  - ncurses=6.3
  - numba=0.53.1
  - openblas=0.3.20
  - openssl=1.1.1o
  - packaging=21.3
  - parso=0.8.3
  - patchelf=0.14.5
  - pathy=0.6.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pkginfo=1.8.2
  - preshed=3.0.6
  - prompt-toolkit=3.0.29
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-lief=0.11.5
  - pycosat=0.6.3
  - pycparser=2.21
  - pydantic=1.8.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.8
  - pysocks=1.7.1
  - python=3.8.13
  - python-libarchive-c=4.0
  - python_abi=3.8
  - pyyaml=6.0
  - readline=8.1
  - rhash=1.4.1
  - ripgrep=13.0.0
  - ruamel_yaml=0.15.80
  - setuptools=59.5.0
  - shellingham=1.4.0
  - six=1.16.0
  - smart_open=5.2.1
  - soupsieve=2.3.1
  - spacy=3.2.4
  - spacy-legacy=3.0.9
  - spacy-loggers=1.0.2
  - sqlite=3.37.1
  - srsly=2.4.3
  - stack_data=0.2.0
  - tensorboardx=2.6.2.2
  - thinc=8.0.15
  - tk=8.6.12
  - traitlets=5.1.1
  - typer=0.4.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - wasabi=0.9.1
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - absl-py==1.0.0
    - accelerate==0.12.0
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.10.11
    - aiosignal==1.3.1
    - alabaster==0.7.12
    - apex==0.1
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - astunparse==1.6.3
    - async-timeout==5.0.1
    - attrs==21.4.0
    - audioread==2.1.9
    - babel==2.9.1
    - bleach==5.0.0
    - cachetools==5.0.0
    - ccimport==0.3.7
    - cloudpickle==2.0.0
    - codecov==2.1.12
    - contextlib2==21.6.0
    - coverage==6.3.2
    - cuda-python==11.6.1
    - cudf==22.2.0a0+309.gdad51a548e
    - cugraph==22.2.0a0+95.g1a25c914
    - cuml==22.2.0a0+109.gc41beba23
    - cumm-cu111==0.2.9
    - cupy-cuda115==9.6.0
    - curl-cffi==0.9.0
    - cycler==0.11.0
    - cython==0.29.28
    - dask==2021.11.2
    - dask-cuda==22.2.0
    - dask-cudf==22.2.0a0+309.gdad51a548e
    - datasets==3.1.0
    - debugpy==1.6.0
    - defusedxml==0.7.1
    - dill==0.3.8
    - distributed==2021.11.2
    - dm-tree==0.1.8
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - docutils==0.17.1
    - dominate==2.9.1
    - einops==0.8.1
    - einx==0.3.0
    - entrypoints==0.4
    - etils==1.3.0
    - eval-type-backport==0.2.2
    - expecttest==0.1.3
    - fastjsonschema==2.15.3
    - fastrlock==0.8
    - fire==0.4.0
    - flask==2.1.1
    - flatbuffers==1.12
    - fonttools==4.32.0
    - frozendict==2.4.6
    - frozenlist==1.5.0
    - fsspec==2024.9.0
    - future==0.18.2
    - gast==0.4.0
    - gitdb==4.0.10
    - gitpython==3.1.31
    - google-auth==2.6.5
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - googleapis-common-protos==1.63.1
    - graphsurgeon==0.4.5
    - grpcio==1.44.0
    - h5py==3.11.0
    - heapdict==1.0.1
    - huggingface-hub==0.29.3
    - hypothesis==4.50.8
    - imageio==2.35.1
    - imagesize==1.3.0
    - importlib-metadata==4.11.3
    - importlib-resources==5.7.0
    - iniconfig==1.1.1
    - install==1.3.5
    - ipdb==0.13.13
    - ipykernel==6.13.0
    - ipython-genutils==0.2.0
    - itsdangerous==2.1.2
    - joblib==1.1.0
    - json5==0.9.6
    - jsonpath==0.82.2
    - jsonschema==4.4.0
    - jupyter-client==7.2.2
    - jupyter-core==4.9.2
    - jupyter-tensorboard==0.2.0
    - jupyterlab==2.3.2
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==1.2.0
    - jupytext==1.13.8
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.2
    - lark==1.1.2
    - lazy-loader==0.4
    - libclang==18.1.1
    - librosa==0.8.1
    - lmdb==1.3.0
    - locket==0.2.1
    - markdown==3.3.6
    - markdown-it-py==3.0.0
    - matplotlib==3.5.1
    - mdit-py-plugins==0.3.0
    - mdurl==0.1.1
    - medpy==0.5.2
    - mistune==0.8.4
    - ml-collections==0.1.1
    - mpmath==1.3.0
    - msgpack==1.0.3
    - multidict==6.1.0
    - multiprocess==0.70.16
    - multitasking==0.0.12
    - nbclient==0.6.0
    - nbconvert==6.5.0
    - nbformat==5.3.0
    - nest-asyncio==1.5.5
    - networkx==3.1
    - ninja==1.10.2.4
    - nltk==3.7
    - notebook==6.4.1
    - numpy==1.24.4
    - nvidia-dali-cuda110==1.12.0
    - nvidia-pyindex==1.0.9
    - nvtx==0.2.4
    - oauthlib==3.2.0
    - onnx==1.11.0
    - opencv-python==4.5.4.60
    - opt-einsum==3.4.0
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - partd==1.2.0
    - pathtools==0.1.2
    - pccm==0.3.4
    - peewee==3.18.3
    - pillow==9.2.0
    - pip==23.0.1
    - platformdirs==4.3.6
    - pluggy==1.0.0
    - polygraphy==0.33.0
    - pooch==1.6.0
    - portalocker==2.5.1
    - prettytable==3.2.0
    - prometheus-client==0.14.1
    - promise==2.3
    - propcache==0.2.0
    - protobuf==3.19.6
    - py==1.11.0
    - pyarrow==17.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybind11==2.9.2
    - pycocotools==2.0+nv0.6.0
    - pydicom==2.4.4
    - pydot==1.4.2
    - pygments==2.19.2
    - pykwalify==1.8.0
    - pynvml==11.4.1
    - pyradiomics==3.1.0
    - pyrsistent==0.18.1
    - pytest==6.2.5
    - pytest-cov==3.0.0
    - pytest-pythonpath==0.7.4
    - python-dateutil==2.8.2
    - python-hostlist==1.21
    - python-nvd3==0.15.0
    - python-slugify==6.1.1
    - pytorch-quantization==2.1.2
    - pytorch-wavelets==1.3.0
    - pytz==2025.2
    - pywavelets==1.4.1
    - pyzmq==22.3.0
    - regex==2022.3.15
    - requests==2.32.4
    - requests-oauthlib==1.3.1
    - resampy==0.2.2
    - retry==0.9.2
    - revtok==0.0.3
    - rich==14.2.0
    - rmm==22.2.0a0+37.gf2b1364
    - rsa==4.8
    - ruamel-yaml==0.18.15
    - ruamel-yaml-clib==0.2.8
    - sacremoses==0.0.49
    - safetensors==0.5.3
    - scikit-image==0.21.0
    - scikit-learn==0.24.2
    - scipy==1.10.1
    - seaborn==0.12.2
    - send2trash==1.8.0
    - sentry-sdk==2.27.0
    - setproctitle==1.3.5
    - simpleitk==2.4.1
    - smmap==5.0.0
    - snowballstemmer==2.2.0
    - sortedcontainers==2.4.0
    - soundfile==0.10.3.post1
    - spconv-cu111==2.1.25
    - sphinx==4.5.0
    - sphinx-glpi-theme==0.3
    - sphinx-rtd-theme==1.0.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - sympy==1.13.3
    - tabulate==0.8.9
    - tblib==1.7.0
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.9.0
    - tensorflow-datasets==4.6.0
    - tensorflow-estimator==2.9.0
    - tensorflow-gan==2.0.0
    - tensorflow-hub==0.16.1
    - tensorflow-io-gcs-filesystem==0.34.0
    - tensorflow-metadata==1.13.0
    - tensorflow-probability==0.12.2
    - tensorrt==8.2.4.2
    - termcolor==2.0.1
    - terminado==0.13.3
    - text-unidecode==1.3
    - tf-keras==2.15.0
    - threadpoolctl==3.1.0
    - tifffile==2023.7.10
    - timm==0.6.12
    - tinycss2==1.1.1
    - toml==0.10.2
    - tomli==2.0.1
    - toolz==0.11.2
    - torch==1.9.1+cu111
    - torchaudio==0.9.1
    - torchdiffeq==0.2.5
    - torchvision==0.10.1+cu111
    - tornado==6.1
    - tqdm==4.64.0
    - treelite==2.2.1
    - treelite-runtime==2.2.1
    - typing-extensions==4.4.0
    - ucx-py==0.21.0a0+37.gbfa0450
    - uff==0.6.9
    - urllib3==1.26.20
    - wandb==0.15.12
    - webencodings==0.5.1
    - websockets==13.1
    - werkzeug==2.1.1
    - wrapt==1.17.2
    - xgboost==1.5.2
    - xxhash==3.5.0
    - yarl==1.15.2
    - yfinance==1.0
    - zict==2.1.0
    - zipp==3.8.0
prefix: /opt/conda
